### PR TITLE
reorg, transpile on prepublish, ignore transpiled - closes #81

### LINKED ISSUE #81: Ship transpiled code
Just installed this from npm and the only available code is the untranspiled components and a bundle.  The transpiled components should be shipped instead.

### PR DESCRIPTION
**Pull request by phated**
No need for the JSX pragma in 0.12

### CODE REVIEW

**Comment by SanderSpies** [comment]
Sorry, but going to have to ask to do this against the 0.13 branch.

**Comment by phated** [comment]
If that's the case, you should switch 0.13 to the default branch on github since you seem to be ignoring master in it's current state.

**Comment by SanderSpies** [comment]
Will do :)

**Comment by SanderSpies** [comment]
Apologies btw. for causing unnecessary extra work.

**Comment by phated** [comment]
Closing in favor of #87

**Pull request closed without merging**
